display-name: 'SimpleRegions'
default-owner-limit: 1
default-buy-sign-line-zero-color: '#136F63'
default-buy-sign-line-zero: '[RENT]'
region-type-configuration:
  BlackMarket:
    remove-items-on-new-owner: true
  CitizenYard:
    upkeep-interval: 2w
    upkeep-cost: 500000
  PrestigeCell:
    owner-limit: 3
  PrisonCell:
    owner-limit: 5