chat-prefix: '&8[&6SimpleRegions&8]&r >> '
sign-line-zero: '[SimpleRegions]'
sign-gui-title: 'Purchase Region'
region-types:
  - PrisonCell
  - BlackMarket
  - Courtyard-Small
  - Courtyard-Large
region-type-configuration:
  PrisonCell:
    buy-sign-line-zero: '&2[RENT]'
    remove-items-on-expiry: false
  BlackMarket:
    remove-items-on-expiry: true
  CourtYard-Small:
    upkeep: true
    upkeep-interval: 1d
    upkeep-cost: 1000
  CourtYard-Large:
    upkeep: true
    upkeep-interval: 1d
    upkeep-cost: 25000