name: SimpleRegions
version: '${version}'
main: moe.krp.simpleregions.SimpleRegions
api-version: '1.18'
depend:
  - WorldEdit
  - Vault
commands:
  SimpleRegions:
    aliases: [sr, simpler, sregions]
    description: SimpleRegions base command
    usage: /<command> [subcommand]
permissions:
  SimpleRegions.*:
    description: SimpleRegions base permission
    children:
      SimpleRegions.create:
        description: Allows player to create a new region definition
      SimpleRegions.delete:
        description: Allows player to delete a region definition
      SimpleRegions.info:
        description: Allows player to view information about a region definition
      SimpleRegions.sign:
        description: Allows player to create, modify, or delete a region sign
        children:
            SimpleRegions.sign.create:
                description: Allows player to create a region sign
            SimpleRegions.sign.modify:
                description: Allows player to modify a region sign
            SimpleRegions.sign.delete:
                description: Allows player to delete a region sign