name: SimpleRegions
version: '${version}'
main: moe.krp.simpleregions.SimpleRegions
api-version: '1.18'
depend:
  - WorldEdit
  - Vault
commands:
  SimpleRegions:
    aliases: [sr, simpler, sregions]
    description: SimpleRegions base command
    usage: /<command> [subcommand]
    permission: SimpleRegions.*
    permission-message: You do not have permission to use this command
permissions:
  SimpleRegions.*:
    default: op
    description: SimpleRegions base permission
    children:
      SimpleRegions.bypass:
        description: Allows player to bypass region protection
      SimpleRegions.create:
        description: Allows player to create a new region definition
      SimpleRegions.delete:
        description: Allows player to delete a region definition
      SimpleRegions.info:
        description: Allows player to view information about a region definition
      SimpleRegions.setOwner:
        description: Allows player to set the owner of a region definition
      SimpleRegions.clearOwner:
        description: Allows player to clear the owner of a region definition
      SimpleRegions.setType:
        description: Allows player to set the type of a region definition
      SimpleRegions.sign:
        description: Allows player to create, modify, or delete a region sign
        children:
            SimpleRegions.sign.create:
                description: Allows player to create a region sign